# Generated by Django 2.0.5 on 2023-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='static/media/reviews/default_image.jpg', upload_to='reviews/'),
        ),
    ]
