# Generated by Django 2.0.5 on 2023-11-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231121_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='ReviewImage',
        ),
        migrations.RenameField(
            model_name='reviewimage',
            old_name='images',
            new_name='image',
        ),
    ]
