# Generated by Django 2.0.5 on 2023-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231121_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('job_title', models.TextField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='card/')),
            ],
        ),
    ]
